export interface MasterSpecies {
  id: string;
  common_name: string;
  scientific_name: string;
  endemic_status: string;
  habitat: string;
  guild: string;
  vocal_activity: string;
  iucn_status: 'Least Concern' | 'Near Threatened' | 'Vulnerable' | 'Endangered' | 'Critically Endangered' | 'Data Deficient';
  foraging_stratum: string;
  indicator_group: string;
  birdnet_label: string;
  image_url: string;
  detections_count: number;
}

export const SPECIES_MASTER_LIST: MasterSpecies[] = [
  {
    "id": "spc-001",
    "common_name": "Ashy Drongo",
    "scientific_name": "Dicrurus leucophaeus",
    "endemic_status": "No",
    "habitat": "Open forests, forest edges, plantations, secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Dicrurus_leucophaeus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Ashy_drongo_in_Latpanchar_April_2024_by_Tisha_Mukherjee_01.jpg",
    "detections_count": 15000
  },
  {
    "id": "spc-002",
    "common_name": "Ashy Prinia",
    "scientific_name": "Prinia socialis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Prinia_socialis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Ashy_Prinia_in_Ajodhya_Hills_July_2024_by_Tisha_Mukherjee_01.jpg",
    "detections_count": 14580
  },
  {
    "id": "spc-003",
    "common_name": "Ashy Woodswallow",
    "scientific_name": "Artamus fuscus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Artamus_fuscus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/73/Av_Ashy_Woodswallow_THAI_JG.jpg",
    "detections_count": 14160
  },
  {
    "id": "spc-004",
    "common_name": "Asian Brown Flycatcher",
    "scientific_name": "Muscicapa dauurica",
    "endemic_status": "No",
    "habitat": "Shaded woodland, forest edges, plantations, gardens",
    "guild": "Insectivore",
    "vocal_activity": "Low",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (lower to midstory)",
    "indicator_group": "General",
    "birdnet_label": "Muscicapa_dauurica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Asian_brown_flycatcher_%28Muscicapa_dauurica_siamensis%29_Angkor_2.jpg/3840px-Asian_brown_flycatcher_%28Muscicapa_dauurica_siamensis%29_Angkor_2.jpg",
    "detections_count": 13740
  },
  {
    "id": "spc-005",
    "common_name": "Asian Emerald Dove",
    "scientific_name": "Chalcophaps indica",
    "endemic_status": "No",
    "habitat": "Dense evergreen and semi-evergreen forests",
    "guild": "Granivore\u2013frugivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily ground-feeding",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Chalcophaps_indica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Asian_Emerald_Dove_0A2A7379.jpg/3840px-Asian_Emerald_Dove_0A2A7379.jpg",
    "detections_count": 13320
  },
  {
    "id": "spc-006",
    "common_name": "Asian Koel",
    "scientific_name": "Eudynamys scolopaceus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Eudynamys_scolopaceus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Asian_koel.jpg",
    "detections_count": 12900
  },
  {
    "id": "spc-007",
    "common_name": "Asian Palm-Swift",
    "scientific_name": "Cypsiurus balasiensis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Cypsiurus_balasiensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Asian_Palm_Swift_Cypsiurus_balasiensis_in_flight_02.JPG",
    "detections_count": 12480
  },
  {
    "id": "spc-008",
    "common_name": "Bank Swallow",
    "scientific_name": "Riparia riparia",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Riparia_riparia",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Sand_martin_%28Riparia_riparia%29%2C_Guidel-Plage%2C_Brittany%2C_France_%2819765483180%29.jpg",
    "detections_count": 12060
  },
  {
    "id": "spc-009",
    "common_name": "Black Drongo",
    "scientific_name": "Dicrurus macrocercus",
    "endemic_status": "No",
    "habitat": "Open habitats: agricultural fields, grasslands, scrub",
    "guild": "Insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Aerial / low arboreal interface",
    "indicator_group": "General",
    "birdnet_label": "Dicrurus_macrocercus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Bdrongo-Sandeep1.jpg",
    "detections_count": 11640
  },
  {
    "id": "spc-010",
    "common_name": "Black-crowned Night-Heron",
    "scientific_name": "Nycticorax nycticorax",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Carnivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Nycticorax_nycticorax",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a1/Nycticorax_nycticorax_457953189.jpg",
    "detections_count": 11220
  },
  {
    "id": "spc-011",
    "common_name": "Black-headed Cuckooshrike",
    "scientific_name": "Lalage melanoptera",
    "endemic_status": "No",
    "habitat": "Open forests, deciduous woodland, forest edges",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy specialist)",
    "indicator_group": "General",
    "birdnet_label": "Lalage_melanoptera",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Cuckooshrike-blackheaded.jpg",
    "detections_count": 10800
  },
  {
    "id": "spc-012",
    "common_name": "Black-hooded Oriole",
    "scientific_name": "Oriolus xanthornus",
    "endemic_status": "No",
    "habitat": "Open woodlands, forest edges, plantations, gardens",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "General",
    "birdnet_label": "Oriolus_xanthornus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Black-hooded_Oriole_in_Rabindra_Sarobar_January_2025_by_Tisha_Mukherjee_01.jpg/3840px-Black-hooded_Oriole_in_Rabindra_Sarobar_January_2025_by_Tisha_Mukherjee_01.jpg",
    "detections_count": 10380
  },
  {
    "id": "spc-013",
    "common_name": "Black-naped Monarch",
    "scientific_name": "Hypothymis azurea",
    "endemic_status": "No",
    "habitat": "Dense forests (evergreen, semi-evergreen, moist deciduous)",
    "guild": "Insectivore (aerial sallier)",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (lower to midstory specialist)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Hypothymis_azurea",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Hypothymis_azurea_-_Kaeng_Krachan.jpg/3840px-Hypothymis_azurea_-_Kaeng_Krachan.jpg",
    "detections_count": 9960
  },
  {
    "id": "spc-014",
    "common_name": "Black-rumped Flameback",
    "scientific_name": "Dinopium benghalense",
    "endemic_status": "No",
    "habitat": "Open forests, dry deciduous woodland, plantations, groves",
    "guild": "Insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (trunk specialist)",
    "indicator_group": "General",
    "birdnet_label": "Dinopium_benghalense",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a5/BR-FlamebackM-Sandeep.jpg",
    "detections_count": 9540
  },
  {
    "id": "spc-015",
    "common_name": "Blue-tailed Bee-eater",
    "scientific_name": "Merops philippinus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Merops_philippinus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Blue-tailed_Bee-eater_in_Sundarbans_National_Park_July_2025_by_Tisha_Mukherjee_03.jpg",
    "detections_count": 9120
  },
  {
    "id": "spc-016",
    "common_name": "Blyth's Reed Warbler",
    "scientific_name": "Acrocephalus dumetorum",
    "endemic_status": "No",
    "habitat": "Dense shrubs, thickets, reedbeds, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Low arboreal / shrub layer specialist",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Acrocephalus_dumetorum",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Blyth%27s_Reed_Warbler_in_Baruipur_December_2024_by_Tisha_Mukherjee_02.jpg",
    "detections_count": 8700
  },
  {
    "id": "spc-017",
    "common_name": "Brahminy Starling",
    "scientific_name": "Sturnia pagodarum",
    "endemic_status": "No",
    "habitat": "Open woodlands, dry scrub, agricultural lands, orchards",
    "guild": "Omnivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (low to midstory) with occasional ground use",
    "indicator_group": "General",
    "birdnet_label": "Sturnia_pagodarum",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Brahminy_starling_-_Vadodara_2021-06-22.jpg",
    "detections_count": 8280
  },
  {
    "id": "spc-018",
    "common_name": "Bronzed Drongo",
    "scientific_name": "Dicrurus aeneus",
    "endemic_status": "No",
    "habitat": "Dense evergreen and semi-evergreen forests",
    "guild": "Insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory specialist, sometimes lower canopy)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Dicrurus_aeneus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Bronzed-Drongo-Sandeep.jpg",
    "detections_count": 7860
  },
  {
    "id": "spc-019",
    "common_name": "Brown Shrike",
    "scientific_name": "Lanius cristatus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Lanius_cristatus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/64/Lanius_cristatus_-_Surin.jpg",
    "detections_count": 7440
  },
  {
    "id": "spc-020",
    "common_name": "Brown-breasted Flycatcher",
    "scientific_name": "Muscicapa muttui",
    "endemic_status": "No",
    "habitat": "Dense evergreen and semi-evergreen forests",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower understorey",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Muscicapa_muttui",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Brown-breasted_flycatcher_%28Muscicapa_muttui%29.jpg",
    "detections_count": 7020
  },
  {
    "id": "spc-021",
    "common_name": "Brown-cheeked Fulvetta",
    "scientific_name": "Alcippe poioicephala",
    "endemic_status": "No",
    "habitat": "Dense understorey of evergreen and moist deciduous forests",
    "guild": "Insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower understorey specialist (arboreal, near-ground)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Alcippe_poioicephala",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Alcippe_poioicephala_davisoni_-_Kaeng_Krachan.jpg",
    "detections_count": 6600
  },
  {
    "id": "spc-022",
    "common_name": "Changeable Hawk-Eagle",
    "scientific_name": "Nisaetus cirrhatus",
    "endemic_status": "No",
    "habitat": "Forests (evergreen, semi-evergreen, moist and dry deciduous)",
    "guild": "Carnivore",
    "vocal_activity": "Low to Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal + aerial predator",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Nisaetus_cirrhatus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Changeable_Hawk_Eagle_Bandipur.jpg",
    "detections_count": 6180
  },
  {
    "id": "spc-023",
    "common_name": "Chestnut-headed Bee-eater",
    "scientific_name": "Merops leschenaulti",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Merops_leschenaulti",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Chestnut-headed_bee-eater_%28Merops_leschenaulti%29_Yala.jpg",
    "detections_count": 5760
  },
  {
    "id": "spc-024",
    "common_name": "Cinereous Tit",
    "scientific_name": "Parus cinereus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Parus_cinereus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Cinereous_tit_%28Parus_cinereus%29_Photograph_by_Shantanu_Kuveskar.jpg",
    "detections_count": 5340
  },
  {
    "id": "spc-025",
    "common_name": "Common Chiffchaff",
    "scientific_name": "Phylloscopus collybita",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Phylloscopus_collybita",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Common_Chiffchaff_2025_04_04_01.jpg/3840px-Common_Chiffchaff_2025_04_04_01.jpg",
    "detections_count": 4920
  },
  {
    "id": "spc-026",
    "common_name": "Common Greenshank",
    "scientific_name": "Tringa nebularia",
    "endemic_status": "No",
    "habitat": "Wetlands: shallow lakes, marshes, estuaries, mudflats, river edges",
    "guild": "Carnivore (aquatic invertebrate feeder)",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground/water feeder",
    "indicator_group": "General",
    "birdnet_label": "Tringa_nebularia",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Common-Greenshank.jpg",
    "detections_count": 4500
  },
  {
    "id": "spc-027",
    "common_name": "Common Hawk-Cuckoo",
    "scientific_name": "Hierococcyx varius",
    "endemic_status": "No",
    "habitat": "Open woodlands, forest edges, groves, gardens",
    "guild": "Insectivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "General",
    "birdnet_label": "Hierococcyx_varius",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Cuculus_varius_India.jpg",
    "detections_count": 4080
  },
  {
    "id": "spc-028",
    "common_name": "Common Iora",
    "scientific_name": "Aegithina tiphia",
    "endemic_status": "No",
    "habitat": "Open woodlands, scrub, forest edges, plantations, gardens",
    "guild": "Insectivore (foliage gleaner)",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (lower to midstory)",
    "indicator_group": "General",
    "birdnet_label": "Aegithina_tiphia",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/87/Common-ioraM-Sandeep.jpg",
    "detections_count": 3660
  },
  {
    "id": "spc-029",
    "common_name": "Common Kingfisher",
    "scientific_name": "Alcedo atthis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Carnivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Alcedo_atthis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Alcedo_atthis_-England-8_%28cropped%29.jpg",
    "detections_count": 3240
  },
  {
    "id": "spc-030",
    "common_name": "Common Myna",
    "scientific_name": "Acridotheres tristis",
    "endemic_status": "No",
    "habitat": "Urban, semi-urban, agricultural landscapes",
    "guild": "Omnivore (highly generalist)",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily ground-feeding with arboreal use",
    "indicator_group": "General",
    "birdnet_label": "Acridotheres_tristis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Acridotheres_tristis00.jpg",
    "detections_count": 2820
  },
  {
    "id": "spc-031",
    "common_name": "Common Rosefinch",
    "scientific_name": "Carpodacus erythrinus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Carpodacus_erythrinus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/19/Carpodacus_erythrinus_284921386.jpg",
    "detections_count": 2400
  },
  {
    "id": "spc-032",
    "common_name": "Common Sandpiper",
    "scientific_name": "Actitis hypoleucos",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Actitis_hypoleucos",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Actitis_hypoleucos_-_Laem_Pak_Bia.jpg",
    "detections_count": 1980
  },
  {
    "id": "spc-033",
    "common_name": "Common Snipe",
    "scientific_name": "Gallinago gallinago",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Gallinago_gallinago",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Common_snipe_%28Gallinago_gallinago%29_2022.jpg/3840px-Common_snipe_%28Gallinago_gallinago%29_2022.jpg",
    "detections_count": 1560
  },
  {
    "id": "spc-034",
    "common_name": "Common Tailorbird",
    "scientific_name": "Orthotomus sutorius",
    "endemic_status": "No",
    "habitat": "Dense shrubs, thickets, gardens, scrublands",
    "guild": "Insectivore (gleaner)",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower shrub layer specialist (low arboreal)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Orthotomus_sutorius",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/93/Common_tailorbird_%28Orthotomus_sutorius%29.jpg",
    "detections_count": 1140
  },
  {
    "id": "spc-035",
    "common_name": "Common Woodshrike",
    "scientific_name": "Tephrodornis pondicerianus",
    "endemic_status": "No",
    "habitat": "Open woodlands, dry deciduous forests, scrub, plantations",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "General",
    "birdnet_label": "Tephrodornis_pondicerianus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Common_Woodshrike_%28Tephrodornis_pondicerianus%29_Photograph_By_Shantanu_Kuveskar.jpg",
    "detections_count": 720
  },
  {
    "id": "spc-036",
    "common_name": "Coppersmith Barbet",
    "scientific_name": "Psilopogon haemacephalus",
    "endemic_status": "No",
    "habitat": "Open woodlands, gardens, plantations, urban and semi-urban areas",
    "guild": "Frugivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal",
    "indicator_group": "General",
    "birdnet_label": "Psilopogon_haemacephalus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Coppersmith_Barbet_%28Megalaima_haemacephala%29_by_Shantanu_Kuveskar.jpg",
    "detections_count": 300
  },
  {
    "id": "spc-037",
    "common_name": "Crested Serpent-Eagle",
    "scientific_name": "Spilornis cheela",
    "endemic_status": "No",
    "habitat": "Forests: evergreen, semi-evergreen, moist and dry deciduous",
    "guild": "Carnivore (reptile specialist)",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal + ground-oriented hunting",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Spilornis_cheela",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/37/Spilornis_cheela_%28Bandipur%2C_2008%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-038",
    "common_name": "Crimson-backed Sunbird",
    "scientific_name": "Leptocoma minima",
    "endemic_status": "Yes",
    "habitat": "Evergreen and shola forests",
    "guild": "Nectarivore (primary) + insectivore (secondary)",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (lower to midstory)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Leptocoma_minima",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Crimson-backed_sunbird_or_small_sunbird_%28Leptocoma_minima%29_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-039",
    "common_name": "Dunlin",
    "scientific_name": "Calidris alpina",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Calidris_alpina",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/39/Dunlin_%28Calidris_alpina%29_in_the_Delaware_Bay_at_Heislerville_Wildlife_Management_Area%2C_New_Jersey%2C_USA.png",
    "detections_count": 150
  },
  {
    "id": "spc-040",
    "common_name": "Eurasian Coot",
    "scientific_name": "Fulica atra",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Fulica_atra",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Eurasian_Coot_2023_11_25_03.jpg/3840px-Eurasian_Coot_2023_11_25_03.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-041",
    "common_name": "Eurasian Curlew",
    "scientific_name": "Numenius arquata",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Numenius_arquata",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Eurasian_Curlew.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-042",
    "common_name": "Eurasian Hoopoe",
    "scientific_name": "Upupa epops",
    "endemic_status": "No",
    "habitat": "Open habitats: grasslands, scrub, agricultural fields, gardens",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding (terrestrial specialist)",
    "indicator_group": "General",
    "birdnet_label": "Upupa_epops",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Israel._Eurasian_Hoopoe_%286497645007%29.jpg/3840px-Israel._Eurasian_Hoopoe_%286497645007%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-043",
    "common_name": "Eurasian Moorhen",
    "scientific_name": "Gallinula chloropus",
    "endemic_status": "No",
    "habitat": "Freshwater wetlands: ponds, lakes, marshes, canals",
    "guild": "Omnivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Aquatic/ground interface",
    "indicator_group": "General",
    "birdnet_label": "Gallinula_chloropus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Common_moorhen_%28Gallinula_chloropus%29_France.jpg/3840px-Common_moorhen_%28Gallinula_chloropus%29_France.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-044",
    "common_name": "Flame-throated Bulbul",
    "scientific_name": "Rubigula gularis",
    "endemic_status": "Yes",
    "habitat": "Evergreen and semi-evergreen forests",
    "guild": "Frugivore\u2013insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Rubigula_gularis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Flame-throated_bulbul.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-045",
    "common_name": "Golden-fronted Leafbird",
    "scientific_name": "Chloropsis aurifrons",
    "endemic_status": "No",
    "habitat": "Open forests, forest edges, plantations, gardens",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy specialist)",
    "indicator_group": "General",
    "birdnet_label": "Chloropsis_aurifrons",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Golden_Fronted_Leafbird_Mukulhinge.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-046",
    "common_name": "Gray Francolin",
    "scientific_name": "Ortygornis pondicerianus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Ortygornis_pondicerianus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Grey_Francolin_in_Bhigwan_August_2025_by_Tisha_Mukherjee_04.jpg/3840px-Grey_Francolin_in_Bhigwan_August_2025_by_Tisha_Mukherjee_04.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-047",
    "common_name": "Gray Heron",
    "scientific_name": "Ardea cinerea",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Carnivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Ardea_cinerea",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Grey_heron_2022_03_18_01.jpg/3840px-Grey_heron_2022_03_18_01.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-048",
    "common_name": "Gray Junglefowl",
    "scientific_name": "Gallus sonneratii",
    "endemic_status": "No",
    "habitat": "Dry and moist deciduous forests, scrub forests, forest edges",
    "guild": "Omnivore",
    "vocal_activity": "High (especially dawn/dusk)",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding (terrestrial specialist)",
    "indicator_group": "General",
    "birdnet_label": "Gallus_sonneratii",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/79/Gallus_sonneratii_%28Bandipur%29%2C_crop.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-049",
    "common_name": "Gray Wagtail",
    "scientific_name": "Motacilla cinerea",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Motacilla_cinerea",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Gebirgsstelze_im_Geo-Naturpark_Bergstra%C3%9Fe-Odenwald.jpg/3840px-Gebirgsstelze_im_Geo-Naturpark_Bergstra%C3%9Fe-Odenwald.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-050",
    "common_name": "Gray-bellied Cuckoo",
    "scientific_name": "Cacomantis passerinus",
    "endemic_status": "No",
    "habitat": "Open woodlands, scrub, forest edges, gardens",
    "guild": "Insectivore (caterpillar specialist)",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (low to midstory)",
    "indicator_group": "General",
    "birdnet_label": "Cacomantis_passerinus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Gray-bellied_Cuckoo_in_Bhigwan_August_2025_by_Tisha_Mukherjee_05.jpg/3840px-Gray-bellied_Cuckoo_in_Bhigwan_August_2025_by_Tisha_Mukherjee_05.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-051",
    "common_name": "Gray-breasted Prinia",
    "scientific_name": "Prinia hodgsonii",
    "endemic_status": "No",
    "habitat": "Open scrub, grasslands, fallow fields, agricultural edges",
    "guild": "Insectivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower shrub layer / near-ground (low arboreal)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Prinia_hodgsonii",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/03/Grey-breasted_prinia_%28Prinia_hodgsonii%29_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-052",
    "common_name": "Gray-fronted Green-Pigeon",
    "scientific_name": "Treron affinis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Frugivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Treron_affinis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/90/Treron_pompadora_affinis.JPG",
    "detections_count": 150
  },
  {
    "id": "spc-053",
    "common_name": "Gray-headed Bulbul",
    "scientific_name": "Brachypodius priocephalus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Frugivore/Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Brachypodius_priocephalus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Grey-headed_Bulbul.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-054",
    "common_name": "Greater Coucal",
    "scientific_name": "Centropus sinensis",
    "endemic_status": "No",
    "habitat": "Dense shrubs, thickets, reedbeds, forest edges",
    "guild": "Carnivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground to low understorey (primarily terrestrial)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Centropus_sinensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Greater_coucal_crop.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-055",
    "common_name": "Greater Flameback",
    "scientific_name": "Chrysocolaptes guttacristatus",
    "endemic_status": "No",
    "habitat": "Forests (evergreen, semi-evergreen, moist deciduous)",
    "guild": "Insectivore (wood-boring specialist)",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (trunk and large branch specialist)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Chrysocolaptes_guttacristatus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/86/Chrysocolaptes_guttacristatus%2C_Kaeng_Krachan.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-056",
    "common_name": "Greater Racket-tailed Drongo",
    "scientific_name": "Dicrurus paradiseus",
    "endemic_status": "No",
    "habitat": "Dense forests: evergreen, semi-evergreen, moist deciduous",
    "guild": "Insectivore (aerial sallier + opportunistic generalist)",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Dicrurus_paradiseus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/91/GRTDrongo_Sandeep.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-057",
    "common_name": "Green Sandpiper",
    "scientific_name": "Tringa ochropus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Tringa_ochropus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/92/Green-Sandpiper-Sandeep.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-058",
    "common_name": "Green Warbler",
    "scientific_name": "Phylloscopus nitidus",
    "endemic_status": "No",
    "habitat": "Wooded habitats: forest edges, open forests, plantations, gardens",
    "guild": "Insectivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower shrub layer / near-ground (low arboreal)",
    "indicator_group": "General",
    "birdnet_label": "Phylloscopus_nitidus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/88/Green_warbler.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-059",
    "common_name": "Greenish Warbler",
    "scientific_name": "Phylloscopus trochiloides",
    "endemic_status": "No",
    "habitat": "Wooded habitats: forest edges, plantations, gardens, open forests",
    "guild": "Insectivore",
    "vocal_activity": "Low",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "General",
    "birdnet_label": "Phylloscopus_trochiloides",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Greenish_Warbler_Sikkim_India_11.05.2014.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-060",
    "common_name": "Indian Blackbird",
    "scientific_name": "Turdus simillimus",
    "endemic_status": "No",
    "habitat": "Montane evergreen (shola) forests and moist deciduous forests",
    "guild": "Omnivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding (terrestrial)",
    "indicator_group": "General",
    "birdnet_label": "Turdus_simillimus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Indian_Blackbird_at_Kotagiri.jpg/3840px-Indian_Blackbird_at_Kotagiri.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-061",
    "common_name": "Indian Blue Robin",
    "scientific_name": "Larvivora brunnea",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Larvivora_brunnea",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/de/Larvivora_brunnea%2C_male%2C_Nandi_Hills.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-062",
    "common_name": "Indian Golden Oriole",
    "scientific_name": "Oriolus kundoo",
    "endemic_status": "No",
    "habitat": "Open woodlands, groves, plantations, gardens",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "General",
    "birdnet_label": "Oriolus_kundoo",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/51/IndianGoldenOriole_M.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-063",
    "common_name": "Indian Gray Hornbill",
    "scientific_name": "Ocyceros birostris",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Frugivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Ocyceros_birostris",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Indian_Grey_Hornbill_I_IMG_4051.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-064",
    "common_name": "Indian Nightjar",
    "scientific_name": "Caprimulgus asiaticus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Caprimulgus_asiaticus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Caprimulgus_asiaticus.jpg/3840px-Caprimulgus_asiaticus.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-065",
    "common_name": "Indian Paradise-Flycatcher",
    "scientific_name": "Terpsiphone paradisi",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Terpsiphone_paradisi",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Indian_paradise_flycatcher_%282018%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-066",
    "common_name": "Indian Peafowl",
    "scientific_name": "Pavo cristatus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Carnivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Pavo_cristatus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Peacock_on_tree_%2852077240794%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-067",
    "common_name": "Indian Pitta",
    "scientific_name": "Pitta brachyura",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Pitta_brachyura",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Indian_pitta_%28Pitta_brachyura%29_Photograph_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-068",
    "common_name": "Indian Robin",
    "scientific_name": "Copsychus fulicatus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Copsychus_fulicatus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/28/Indian_Robin_%28Copsychus_fulicatus%29%2C_Koottanad%2C_Palakkad_district%2C_Kerala_1.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-069",
    "common_name": "Indian Roller",
    "scientific_name": "Coracias benghalensis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Coracias_benghalensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/06/Indian_roller_-_Timbi_Lake%2C_Vadodara_2023-12-03.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-070",
    "common_name": "Indian Scimitar-Babbler",
    "scientific_name": "Pomatorhinus horsfieldii",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily ground-feeding",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Pomatorhinus_horsfieldii",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d6/IndianScimitarBabbler.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-071",
    "common_name": "Indian White-eye",
    "scientific_name": "Zosterops palpebrosus",
    "endemic_status": "No",
    "habitat": "Open woodlands, plantations, gardens, forest edges",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal",
    "indicator_group": "General",
    "birdnet_label": "Zosterops_palpebrosus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Indian_white-eye_%28Zosterops_palpebrosus_egregius%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-072",
    "common_name": "Jerdon's Bushlark",
    "scientific_name": "Mirafra affinis",
    "endemic_status": "No",
    "habitat": "Open grasslands, scrub, fallow fields, dry open habitats",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding",
    "indicator_group": "General",
    "birdnet_label": "Mirafra_affinis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/90/Jerdon%27s_bushlark_%28Mirafra_affinis%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-073",
    "common_name": "Jungle Babbler",
    "scientific_name": "Argya striata",
    "endemic_status": "No",
    "habitat": "Open woodlands, scrub, gardens, agricultural lands",
    "guild": "Omnivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground + low understorey (terrestrial\u2013low arboreal)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Argya_striata",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Jungle_babbler_%28Turdoides_striata%29_Photograph_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-074",
    "common_name": "Jungle Myna",
    "scientific_name": "Acridotheres fuscus",
    "endemic_status": "No",
    "habitat": "Open areas such as farmland, fields, and parks.",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding + arboreal use (mixed)",
    "indicator_group": "General",
    "birdnet_label": "Acridotheres_fuscus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Jungle_Myna_%28Acridotheres_fuscus%29_on_Kapok_%28Ceiba_pentandra%29_in_Kolkata_I_IMG_1340.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-075",
    "common_name": "Jungle Owlet",
    "scientific_name": "Glaucidium radiatum",
    "endemic_status": "No",
    "habitat": "Open forests, dry and moist deciduous forests, wooded groves",
    "guild": "Carnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (low to midstory perch hunter)",
    "indicator_group": "General",
    "birdnet_label": "Glaucidium_radiatum",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Jungle_owlet_3.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-076",
    "common_name": "Jungle Prinia",
    "scientific_name": "Prinia sylvatica",
    "endemic_status": "No",
    "habitat": "Dry scrub, grasslands, open bushy habitats",
    "guild": "Insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower vegetation",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Prinia_sylvatica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Jungle_Prinia_in_Saswad_August_2025_by_Tisha_Mukherjee_02.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-077",
    "common_name": "Large-billed Crow",
    "scientific_name": "Corvus macrorhynchos",
    "endemic_status": "No",
    "habitat": "Highly adaptable: forests, forest edges, urban areas, villages, plantations",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Mixed (arboreal + ground + aerial)",
    "indicator_group": "General",
    "birdnet_label": "Corvus_macrorhynchos",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Jungle_crow_%28Close-up_of_the_head_area%29%2C_Tenn%C5%8Dji_Park%2C_Osaka_II.jpg/3840px-Jungle_crow_%28Close-up_of_the_head_area%29%2C_Tenn%C5%8Dji_Park%2C_Osaka_II.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-078",
    "common_name": "Large-billed Leaf Warbler",
    "scientific_name": "Phylloscopus magnirostris",
    "endemic_status": "No",
    "habitat": "Forest edges, wooded ravines, streamside vegetation",
    "guild": "Insectivore",
    "vocal_activity": "Low",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (lower to midstory)",
    "indicator_group": "General",
    "birdnet_label": "Phylloscopus_magnirostris",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/dc/Large-billed_Leaf_Warbler_%28Phylloscopus_magnirostris%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-079",
    "common_name": "Laughing Dove",
    "scientific_name": "Streptopelia senegalensis",
    "endemic_status": "No",
    "habitat": "Open habitats: scrub, agricultural fields, villages, urban areas",
    "guild": "Granivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding (terrestrial)",
    "indicator_group": "General",
    "birdnet_label": "Streptopelia_senegalensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/140_Laughing_dove_in_Twyfelfontein_Photo_by_Giles_Laurent.jpg/3840px-140_Laughing_dove_in_Twyfelfontein_Photo_by_Giles_Laurent.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-080",
    "common_name": "Lesser Whitethroat",
    "scientific_name": "Curruca curruca",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Curruca_curruca",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/74/%D0%A1%D0%BB%D0%B0%D0%B2%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%88%D0%BA%D0%B0_%28Sylvia_curruca%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-081",
    "common_name": "Little Grebe",
    "scientific_name": "Tachybaptus ruficollis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Tachybaptus_ruficollis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/84/Little_grebe_Zwergtaucher.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-082",
    "common_name": "Loten's Sunbird",
    "scientific_name": "Cinnyris lotenius",
    "endemic_status": "No",
    "habitat": "Open woodlands, scrub, gardens, plantations",
    "guild": "Nectarivore+ insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (low to midstory)",
    "indicator_group": "General",
    "birdnet_label": "Cinnyris_lotenius",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Loten%27sSunbird%28M%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-083",
    "common_name": "Malabar Barbet",
    "scientific_name": "Psilopogon malabaricus",
    "endemic_status": "Yes",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Frugivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Psilopogon_malabaricus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/11/Malabar_Barbet_%28Psilopogon_malabaricus%29_-_Male_-_Sakleshpur_-_India_-2009.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-084",
    "common_name": "Malabar Gray Hornbill",
    "scientific_name": "Ocyceros griseus",
    "endemic_status": "Yes",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Frugivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Ocyceros_griseus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Ocyceros_griseus_-India-6-4c.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-085",
    "common_name": "Malabar Parakeet",
    "scientific_name": "Psittacula columboides",
    "endemic_status": "Yes",
    "habitat": "Evergreen and semi-evergreen forests",
    "guild": "Herbivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (canopy specialist)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Psittacula_columboides",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Malabar_or_Blue-winged_parakeet_%28Psittacula_columboides%29_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-086",
    "common_name": "Malabar Whistling-Thrush",
    "scientific_name": "Myophonus horsfieldii",
    "endemic_status": "Yes",
    "habitat": "Forest streams, riparian zones, waterfalls",
    "guild": "Omnivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground / rock surfaces near water",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Myophonus_horsfieldii",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Back_Whistling_Thrush_Sheikalmudi_Feb26_A7CR_10052.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-087",
    "common_name": "Malabar Woodshrike",
    "scientific_name": "Tephrodornis sylvicola",
    "endemic_status": "Yes",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Tephrodornis_sylvicola",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/de/Blissful_Rare_Sighting_Malabar_Woodshrik_01%2C_crop.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-088",
    "common_name": "Nilgiri Flowerpecker",
    "scientific_name": "Dicaeum concolor",
    "endemic_status": "Yes",
    "habitat": "Evergreen and semi-evergreen forests",
    "guild": "Frugivore\u2013nectarivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (canopy to upper midstory)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Dicaeum_concolor",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Dicaeum_concolor.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-089",
    "common_name": "Orange Minivet",
    "scientific_name": "Pericrocotus flammeus",
    "endemic_status": "No",
    "habitat": "Forests (evergreen, semi-evergreen, moist deciduous)",
    "guild": "Insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy specialist)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Pericrocotus_flammeus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Orange_Minivet%2C_Ganeshgudi%2C_28_FEB_2016%2C_Vimal_Rajyaguru.jpg/3840px-Orange_Minivet%2C_Ganeshgudi%2C_28_FEB_2016%2C_Vimal_Rajyaguru.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-090",
    "common_name": "Orange-headed Thrush",
    "scientific_name": "Geokichla citrina",
    "endemic_status": "No",
    "habitat": "Dense forests: evergreen, semi-evergreen, moist deciduous",
    "guild": "Omnivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding (terrestrial specialist)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Geokichla_citrina",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Zoothera_citrina_-_Khao_Yai.jpg/3840px-Zoothera_citrina_-_Khao_Yai.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-091",
    "common_name": "Oriental Magpie-Robin",
    "scientific_name": "Copsychus saularis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Copsychus_saularis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Oriental_magpie-robin_%28Copsychus_saularis_ceylonensis%29_male.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-092",
    "common_name": "Osprey",
    "scientific_name": "Pandion haliaetus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Pandion_haliaetus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Osprey_Perched_Snag_Heislerville.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-093",
    "common_name": "Pale-billed Flowerpecker",
    "scientific_name": "Dicaeum erythrorhynchos",
    "endemic_status": "No",
    "habitat": "Open woodlands, gardens, plantations, forest edges",
    "guild": "Frugivore\u2013nectarivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (upper shrub to canopy)",
    "indicator_group": "General",
    "birdnet_label": "Dicaeum_erythrorhynchos",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Pale_billed_Flowerpecker2.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-094",
    "common_name": "Plum-headed Parakeet",
    "scientific_name": "Psittacula cyanocephala",
    "endemic_status": "No",
    "habitat": "Open forests, woodland edges, plantations, groves",
    "guild": "Herbivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (canopy to upper midstory)",
    "indicator_group": "General",
    "birdnet_label": "Psittacula_cyanocephala",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/104_Male_Plum-headed_parakeet_eating_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg/3840px-104_Male_Plum-headed_parakeet_eating_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-095",
    "common_name": "Puff-throated Babbler",
    "scientific_name": "Pellorneum ruficeps",
    "endemic_status": "No",
    "habitat": "Dense forests: evergreen, semi-evergreen, moist deciduous",
    "guild": "Insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Pellorneum_ruficeps",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pellorneum_ruficeps_-_Khao_Yai.jpg/3840px-Pellorneum_ruficeps_-_Khao_Yai.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-096",
    "common_name": "Purple Sunbird",
    "scientific_name": "Cinnyris asiaticus",
    "endemic_status": "No",
    "habitat": "Open habitats: gardens, scrub, agricultural areas, urban spaces",
    "guild": "Nectarivore + insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (low to midstory)",
    "indicator_group": "General",
    "birdnet_label": "Cinnyris_asiaticus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Purple_Sunbird_%28Nectarinia_asiatica%29-_Male_%28Breeding%29_on_Kapok_%28Ceiba_pentandra%29_in_Kolkata_I_IMG_1893.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-097",
    "common_name": "Purple-rumped Sunbird",
    "scientific_name": "Leptocoma zeylonica",
    "endemic_status": "No",
    "habitat": "Gardens, plantations, forest edges, scrub",
    "guild": "Nectarivore + insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal",
    "indicator_group": "General",
    "birdnet_label": "Leptocoma_zeylonica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5a/PR-SunbirdM-Sandeep.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-098",
    "common_name": "Red Spurfowl",
    "scientific_name": "Galloperdix spadicea",
    "endemic_status": "No",
    "habitat": "Dense evergreen, semi-evergreen, and moist deciduous forests",
    "guild": "Omnivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Galloperdix_spadicea",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/69/RED_SPURFOWL_NHOLE.png",
    "detections_count": 150
  },
  {
    "id": "spc-099",
    "common_name": "Red-rumped Swallow",
    "scientific_name": "Cecropis daurica",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Cecropis_daurica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Red-rumped_swallow_in_Calpe%2C_Spain_-_May_2018_01.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-100",
    "common_name": "Red-vented Bulbul",
    "scientific_name": "Pycnonotus cafer",
    "endemic_status": "No",
    "habitat": "Open habitats: scrub, gardens, agricultural lands, urban areas",
    "guild": "Omnivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Low arboreal + ground (mixed)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Pycnonotus_cafer",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/86/Red-vented_bulbul_-_Jamnagar_2023-11-13.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-101",
    "common_name": "Red-wattled Lapwing",
    "scientific_name": "Vanellus indicus",
    "endemic_status": "No",
    "habitat": "Open habitats: grasslands, agricultural fields, riverbanks, wetlands edges",
    "guild": "Carnivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding",
    "indicator_group": "General",
    "birdnet_label": "Vanellus_indicus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Red-wattled_lapwing_%28Vanellus_indicus%29_Photograph_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-102",
    "common_name": "Red-whiskered Bulbul",
    "scientific_name": "Pycnonotus jocosus",
    "endemic_status": "No",
    "habitat": "Open habitats: scrub, gardens, plantations, forest edges",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Low to midstory arboreal",
    "indicator_group": "General",
    "birdnet_label": "Pycnonotus_jocosus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Red-whiskered_bulbul_-_Pycnonotous_jocosus.png",
    "detections_count": 150
  },
  {
    "id": "spc-103",
    "common_name": "Rufous Treepie",
    "scientific_name": "Dendrocitta vagabunda",
    "endemic_status": "No",
    "habitat": "Open woodlands, forest edges, plantations, gardens",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy) + occasional ground use",
    "indicator_group": "General",
    "birdnet_label": "Dendrocitta_vagabunda",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Rufous_treepie_%28Dendrocitta_vagabunda_vagabunda%29_Jahalana_pair.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-104",
    "common_name": "Rufous Woodpecker",
    "scientific_name": "Micropternus brachyurus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Micropternus_brachyurus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/83/Rufous_woodpecker.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-105",
    "common_name": "Shikra",
    "scientific_name": "Accipiter badius",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Accipiter_badius",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Shikra1.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-106",
    "common_name": "Small Minivet",
    "scientific_name": "Pericrocotus cinnamomeus",
    "endemic_status": "No",
    "habitat": "Open woodlands, scrub, plantations, forest edges",
    "guild": "Insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Pericrocotus_cinnamomeus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/40/Pericrocotus_cinnamomeus%2C_Small_minivet_%28male%29_-_Bangkok_%2825838143941%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-107",
    "common_name": "Southern Hill Myna",
    "scientific_name": "Gracula indica",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Frugivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Gracula_indica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Starling_bird_%28India%2C_2012%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-108",
    "common_name": "Spotted Dove",
    "scientific_name": "Streptopelia chinensis",
    "endemic_status": "No",
    "habitat": "Open habitats: gardens, scrub, agricultural lands, urban areas",
    "guild": "Granivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground-feeding",
    "indicator_group": "General",
    "birdnet_label": "Streptopelia_chinensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Spotted_dove_%28Spilopelia_chinensis_suratensis%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-109",
    "common_name": "Stork-billed Kingfisher",
    "scientific_name": "Pelargopsis capensis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Carnivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Pelargopsis_capensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/01/Stork-billed_Kingfisher_Baranagar_Kolkata_West_Bengal_India_21.04.2014.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-110",
    "common_name": "Sykes's Warbler",
    "scientific_name": "Iduna rama",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Iduna_rama",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Syke%27s_Warbler_%28Hippolais_rama%29_on_Vilaiti_Siris_%28Samanea_saman%29_in_Kolkata_W_IMG_4659.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-111",
    "common_name": "Taiga Flycatcher",
    "scientific_name": "Ficedula albicilla",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Ficedula_albicilla",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/66/Taiga_Flycatcher.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-112",
    "common_name": "Tawny-bellied Babbler",
    "scientific_name": "Dumetia hyperythra",
    "endemic_status": "No",
    "habitat": "Dense undergrowth in evergreen, semi-evergreen, and moist deciduous forests",
    "guild": "Insectivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower shrub layer (low arboreal, near-ground)",
    "indicator_group": "General",
    "birdnet_label": "Dumetia_hyperythra",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Tawny_bellied_warbler_2_by_David_Raju_%28cropped%29.jpg/3840px-Tawny_bellied_warbler_2_by_David_Raju_%28cropped%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-113",
    "common_name": "Thick-billed Flowerpecker",
    "scientific_name": "Dicaeum agile",
    "endemic_status": "No",
    "habitat": "Forest edges, open forests, plantations, gardens",
    "guild": "Frugivore\u2013nectarivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal",
    "indicator_group": "General",
    "birdnet_label": "Dicaeum_agile",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Dicaeum_agile_modestum_-_Kaeng_Krachan.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-114",
    "common_name": "Tickell's Blue Flycatcher",
    "scientific_name": "Cyornis tickelliae",
    "endemic_status": "No",
    "habitat": "Forests (evergreen, semi-evergreen, moist deciduous)",
    "guild": "Insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Lower understorey (arboreal, near-ground)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Cyornis_tickelliae",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tickell%27s_blue_flycatcher_%28Cyornis_tickelliae%29_Photograph_By_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-115",
    "common_name": "Tree Pipit",
    "scientific_name": "Anthus trivialis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Anthus_trivialis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Tree_pipit_-_Jamnagar_2021-10-16.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-116",
    "common_name": "Velvet-fronted Nuthatch",
    "scientific_name": "Sitta frontalis",
    "endemic_status": "No",
    "habitat": "Forests (evergreen, semi-evergreen, moist deciduous)",
    "guild": "Insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (trunk and branch specialist)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Sitta_frontalis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Velvet-fronted_Nuthatch_%E0%A4%AE%E0%A4%96%E0%A4%AE%E0%A4%B2%E0%A5%80_%E0%A4%AE%E0%A4%9F%E0%A5%8D%E0%A4%9F%E0%A4%BE.jpg/3840px-Velvet-fronted_Nuthatch_%E0%A4%AE%E0%A4%96%E0%A4%AE%E0%A4%B2%E0%A5%80_%E0%A4%AE%E0%A4%9F%E0%A5%8D%E0%A4%9F%E0%A4%BE.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-117",
    "common_name": "Verditer Flycatcher",
    "scientific_name": "Eumyias thalassinus",
    "endemic_status": "No",
    "habitat": "Open forests, forest edges, clearings, plantations",
    "guild": "Insectivore",
    "vocal_activity": "Low to Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to open perch level)",
    "indicator_group": "General",
    "birdnet_label": "Eumyias_thalassinus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/56/%E0%A6%85%E0%A6%AE%E0%A7%8D%E0%A6%AC%E0%A6%B0_%E0%A6%9A%E0%A7%81%E0%A6%9F%E0%A6%95%E0%A6%BF_-_Verditer_flycatcher_%28Eumyias_thalassinus%29%2C_Naogaon%2C_Bangladesh.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-118",
    "common_name": "Vernal Hanging-Parrot",
    "scientific_name": "Loriculus vernalis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Loriculus_vernalis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Loriculus_vernalis_-Ganeshgudi%2C_Karnataka%2C_India_-male-8-1c.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-119",
    "common_name": "White-bellied Treepie",
    "scientific_name": "Dendrocitta leucogastra",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Omnivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Dendrocitta_leucogastra",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/White-bellied_treepie_-_Dendrocitta_leucogastra%29.jpg/3840px-White-bellied_treepie_-_Dendrocitta_leucogastra%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-120",
    "common_name": "White-breasted Waterhen",
    "scientific_name": "Amaurornis phoenicurus",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Amaurornis_phoenicurus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Amaurornis_phoenicurus_-_Singapore_Botanic_Gardens.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-121",
    "common_name": "White-browed Bulbul",
    "scientific_name": "Pycnonotus luteolus",
    "endemic_status": "No",
    "habitat": "Dry scrub, open woodland, thorny bushes, degraded forest edges",
    "guild": "Omnivore",
    "vocal_activity": "High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Low arboreal (shrub layer specialist)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Pycnonotus_luteolus",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/db/White_browed_bulbul-4E_%28cropped%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-122",
    "common_name": "White-cheeked Barbet",
    "scientific_name": "Psilopogon viridis",
    "endemic_status": "Yes",
    "habitat": "Evergreen and moist deciduous forests",
    "guild": "Frugivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Psilopogon_viridis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/White-cheeked_barbet_Christ_University_-_Birdwalk_%282%29.jpg/3840px-White-cheeked_barbet_Christ_University_-_Birdwalk_%282%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-123",
    "common_name": "White-throated Kingfisher",
    "scientific_name": "Halcyon smyrnensis",
    "endemic_status": "No",
    "habitat": "wetlands, rivers, lakes, agricultural fields, urban areas",
    "guild": "Carnivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Perch hunter (arboreal + ground/water strike)",
    "indicator_group": "General",
    "birdnet_label": "Halcyon_smyrnensis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c8/White-throated_kingfisher_%28Halcyon_smyrnensis%29_Galle.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-124",
    "common_name": "Yellow-billed Babbler",
    "scientific_name": "Argya affinis",
    "endemic_status": "No",
    "habitat": "Open scrub, dry deciduous woodland, gardens, agricultural lands",
    "guild": "Omnivore",
    "vocal_activity": "Very High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground + low understorey (terrestrial\u2013low arboreal)",
    "indicator_group": "Lantana-associated",
    "birdnet_label": "Argya_affinis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Yellow-billed_babbler_%28Argya_affinis_taprobanus%29.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-125",
    "common_name": "Yellow-browed Bulbul",
    "scientific_name": "Iole indica",
    "endemic_status": "Yes",
    "habitat": "Evergreen and semi-evergreen forests",
    "guild": "Frugivore\u2013insectivore",
    "vocal_activity": "Moderate\u2013High",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Arboreal (midstory to canopy)",
    "indicator_group": "Recovery-associated",
    "birdnet_label": "Iole_indica",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/ac/Yellow-browed_bulbul.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-126",
    "common_name": "Yellow-eyed Babbler",
    "scientific_name": "Chrysomma sinense",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily ground-feeding",
    "indicator_group": "General",
    "birdnet_label": "Chrysomma_sinense",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/da/Yellow-eyed_babbler_%28Chrysomma_sinense%29_Photograph_by_Shantanu_Kuveskar.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-127",
    "common_name": "Yellow-throated Sparrow",
    "scientific_name": "Gymnoris xanthocollis",
    "endemic_status": "No",
    "habitat": "scrub, rocky areas, dry deciduous woodland, agricultural lands",
    "guild": "Granivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Ground + low arboreal",
    "indicator_group": "General",
    "birdnet_label": "Gymnoris_xanthocollis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/00/Petronia_xanthocollis_-Haryana%2C_India_-male-8.jpg",
    "detections_count": 150
  },
  {
    "id": "spc-128",
    "common_name": "Zitting Cisticola",
    "scientific_name": "Cisticola juncidis",
    "endemic_status": "No",
    "habitat": "Forest, woodlands, and secondary growth",
    "guild": "Insectivore",
    "vocal_activity": "Moderate",
    "iucn_status": "Least Concern",
    "foraging_stratum": "Primarily arboreal",
    "indicator_group": "General",
    "birdnet_label": "Cisticola_juncidis",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/31/Zitting_cisticola_2024_04_19_%28cropped%29.jpg",
    "detections_count": 150
  }
];
